import { useState, useCallback, useMemo } from "react";
import { Link } from "react-router-dom";

const STEPS = [
  { id: "identity", label: "Identity", icon: "◆" },
  { id: "model", label: "Model", icon: "⚙" },
  { id: "prompt", label: "Prompt", icon: "✎" },
  { id: "inputs", label: "I/O", icon: "⇄" },
  { id: "tools", label: "Tools", icon: "⚡" },
  { id: "guardrails", label: "Guardrails", icon: "🛡" },
  { id: "memory", label: "Memory", icon: "◉" },
  { id: "preview", label: "Export", icon: "↓" },
];

const MODELS = [
  "claude-sonnet-4-5",
  "claude-opus-4-5",
  "claude-haiku-4-5",
  "gpt-4o",
  "gpt-4o-mini",
  "gemini-2.0-flash",
  "gemini-2.5-pro",
  "deepseek-v3",
  "llama-3.3-70b",
  "custom",
];

const CAPABILITIES = ["tool-use", "vision", "code-execution", "structured-output", "long-context"];
const PROTOCOLS = ["mcp", "function", "api"];
const OUTPUT_FORMATS = ["markdown", "json", "text", "html", "structured"];
const AUTONOMY_LEVELS = ["draft-only", "suggest", "auto-with-review", "full-auto"];
const PERSISTENCE_OPTS = ["host-managed", "ephemeral", "external"];
const CATEGORIES = ["marketing", "research", "content", "finance", "compliance", "support", "engineering", "data", "other"];

const defaultState = {
  name: "",
  version: "1.0.0",
  description: "",
  role: "",
  authorName: "",
  license: "Apache-2.0",
  modelPreferred: "claude-sonnet-4-5",
  modelCustom: "",
  capabilities: ["tool-use"],
  temperature: 0.7,
  maxTokens: 4000,
  promptContent: "You are a helpful AI assistant.\n\nYour role is to...\n\n## Guidelines\n- Be concise and accurate\n- Always cite sources\n- Ask for clarification when needed",
  inputs: [{ name: "", type: "text", required: true, description: "" }],
  outputFormat: "markdown",
  toolsRequired: [{ name: "", protocol: "mcp", description: "", server: "" }],
  toolsOptional: [],
  guardrailsRules: [""],
  maxAutonomy: "draft-only",
  maxIterations: 50,
  maxTokensPerResponse: 4000,
  memoryEnabled: false,
  memoryFields: [{ name: "", type: "text", description: "" }],
  memoryPersistence: "host-managed",
  tags: "",
  category: "content",
};

function generateYAML(s) {
  const model = s.modelPreferred === "custom" ? s.modelCustom : s.modelPreferred;
  const caps = s.capabilities.map((c) => `\n      - "${c}"`).join("");
  
  let inputsBlock = "";
  const validInputs = s.inputs.filter((i) => i.name.trim());
  if (validInputs.length > 0) {
    inputsBlock = `\n  inputs:${validInputs
      .map(
        (i) =>
          `\n    - name: "${i.name}"\n      type: "${i.type}"\n      required: ${i.required}${i.description ? `\n      description: "${i.description}"` : ""}`
      )
      .join("")}`;
  }

  let toolsReqBlock = "";
  const validToolsReq = s.toolsRequired.filter((t) => t.name.trim());
  if (validToolsReq.length > 0) {
    toolsReqBlock = `\n    required:${validToolsReq
      .map(
        (t) =>
          `\n      - name: "${t.name}"\n        protocol: "${t.protocol}"${t.description ? `\n        description: "${t.description}"` : ""}${t.server ? `\n        server: "${t.server}"` : ""}`
      )
      .join("")}`;
  }

  let toolsOptBlock = "";
  const validToolsOpt = s.toolsOptional.filter((t) => t.name.trim());
  if (validToolsOpt.length > 0) {
    toolsOptBlock = `\n    optional:${validToolsOpt
      .map(
        (t) =>
          `\n      - name: "${t.name}"\n        protocol: "${t.protocol}"${t.description ? `\n        description: "${t.description}"` : ""}${t.server ? `\n        server: "${t.server}"` : ""}`
      )
      .join("")}`;
  }

  let toolsBlock = "";
  if (toolsReqBlock || toolsOptBlock) {
    toolsBlock = `\n  tools:${toolsReqBlock}${toolsOptBlock}`;
  }

  const validRules = s.guardrailsRules.filter((r) => r.trim());
  let guardrailsBlock = `\n  guardrails:\n    max_autonomy: "${s.maxAutonomy}"\n    limits:\n      max_iterations: ${s.maxIterations}\n      max_tokens_per_response: ${s.maxTokensPerResponse}`;
  if (validRules.length > 0) {
    guardrailsBlock += `\n    rules:${validRules.map((r) => `\n      - "${r}"`).join("")}`;
  }

  let memoryBlock = "";
  if (s.memoryEnabled) {
    const validFields = s.memoryFields.filter((f) => f.name.trim());
    memoryBlock = `\n  memory:\n    persistence: "${s.memoryPersistence}"`;
    if (validFields.length > 0) {
      memoryBlock += `\n    schema:${validFields
        .map(
          (f) =>
            `\n      - name: "${f.name}"\n        type: "${f.type}"${f.description ? `\n        description: "${f.description}"` : ""}`
        )
        .join("")}`;
    }
  }

  const tags = s.tags
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean);
  const tagsBlock = tags.length > 0 ? `\n  tags: [${tags.map((t) => `"${t}"`).join(", ")}]` : "";

  return `# .fylle manifest — generated by Fylle Agent Builder
fylle_format: "0.1.0"

agent:
  name: "${s.name || "my-agent"}"
  version: "${s.version}"
  description: "${s.description}"${s.role ? `\n  role: "${s.role}"` : ""}

  author:
    name: "${s.authorName}"
  license: "${s.license}"

  model:
    preferred: "${model}"
    minimum_capability:${caps}
    settings:
      temperature: ${s.temperature}
      max_tokens: ${s.maxTokens}

  prompt_file: "agent.md"
${inputsBlock}
  output:
    format: "${s.outputFormat}"
${toolsBlock}
${guardrailsBlock}
${memoryBlock}
${tagsBlock}${s.category ? `\n  category: "${s.category}"` : ""}`;
}

function generateAgentMd(s) {
  return s.promptContent || "You are a helpful AI assistant.";
}

function Field({ label, sub, children }) {
  return (
    <div style={{ marginBottom: 20 }}>
      <label style={{ display: "block", fontSize: 13, fontWeight: 600, color: "#e8e8ed", marginBottom: 4 }}>
        {label}
      </label>
      {sub && <div style={{ fontSize: 11, color: "#8888a0", marginBottom: 6 }}>{sub}</div>}
      {children}
    </div>
  );
}

const inputStyle = {
  width: "100%",
  padding: "10px 12px",
  background: "#111113",
  border: "1px solid #222228",
  borderRadius: 8,
  color: "#e8e8ed",
  fontSize: 13,
  fontFamily: "inherit",
  outline: "none",
  transition: "border-color 0.2s",
};

const monoInputStyle = { ...inputStyle, fontFamily: "'JetBrains Mono', monospace", fontSize: 12 };

const chipBase = {
  padding: "5px 12px",
  borderRadius: 6,
  fontSize: 12,
  fontWeight: 500,
  cursor: "pointer",
  border: "1px solid #222228",
  transition: "all 0.15s",
  userSelect: "none",
};

const chipActive = { ...chipBase, background: "#c8ff0025", borderColor: "#c8ff00", color: "#c8ff00" };
const chipInactive = { ...chipBase, background: "#111113", color: "#8888a0" };

function Chip({ active, onClick, children }) {
  return (
    <button style={active ? chipActive : chipInactive} onClick={onClick}>
      {children}
    </button>
  );
}

function SmallBtn({ onClick, children, danger }) {
  return (
    <button
      onClick={onClick}
      style={{
        padding: "4px 10px",
        fontSize: 11,
        fontWeight: 600,
        borderRadius: 5,
        border: "1px solid",
        borderColor: danger ? "#55223a" : "#222228",
        background: danger ? "#2a111a" : "#111113",
        color: danger ? "#ff6b8a" : "#8888a0",
        cursor: "pointer",
      }}
    >
      {children}
    </button>
  );
}

function StepIdentity({ state, set }) {
  return (
    <>
      <Field label="Agent Name" sub="A slug-friendly name for your agent">
        <input style={monoInputStyle} placeholder="content-curator" value={state.name} onChange={(e) => set("name", e.target.value)} />
      </Field>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
        <Field label="Version">
          <input style={monoInputStyle} placeholder="1.0.0" value={state.version} onChange={(e) => set("version", e.target.value)} />
        </Field>
        <Field label="License">
          <input style={inputStyle} placeholder="Apache-2.0" value={state.license} onChange={(e) => set("license", e.target.value)} />
        </Field>
      </div>
      <Field label="Description" sub="What does this agent do?">
        <textarea style={{ ...inputStyle, minHeight: 60, resize: "vertical" }} placeholder="Finds and curates relevant content for newsletters" value={state.description} onChange={(e) => set("description", e.target.value)} />
      </Field>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
        <Field label="Role" sub="Used by CrewAI, AutoGen, UI">
          <input style={inputStyle} placeholder="Research Specialist" value={state.role} onChange={(e) => set("role", e.target.value)} />
        </Field>
        <Field label="Author">
          <input style={inputStyle} placeholder="Your name" value={state.authorName} onChange={(e) => set("authorName", e.target.value)} />
        </Field>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
        <Field label="Category">
          <select style={inputStyle} value={state.category} onChange={(e) => set("category", e.target.value)}>
            {CATEGORIES.map((c) => (
              <option key={c} value={c}>{c}</option>
            ))}
          </select>
        </Field>
        <Field label="Tags" sub="Comma-separated">
          <input style={inputStyle} placeholder="marketing, research, content" value={state.tags} onChange={(e) => set("tags", e.target.value)} />
        </Field>
      </div>
    </>
  );
}

function StepModel({ state, set }) {
  return (
    <>
      <Field label="Preferred Model" sub="Suggestion — the runtime can override">
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
          {MODELS.map((m) => (
            <Chip key={m} active={state.modelPreferred === m} onClick={() => set("modelPreferred", m)}>
              {m}
            </Chip>
          ))}
        </div>
      </Field>
      {state.modelPreferred === "custom" && (
        <Field label="Custom Model ID">
          <input style={monoInputStyle} placeholder="my-model/v1" value={state.modelCustom} onChange={(e) => set("modelCustom", e.target.value)} />
        </Field>
      )}
      <Field label="Minimum Capabilities" sub="What the model MUST support">
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
          {CAPABILITIES.map((c) => (
            <Chip
              key={c}
              active={state.capabilities.includes(c)}
              onClick={() =>
                set(
                  "capabilities",
                  state.capabilities.includes(c) ? state.capabilities.filter((x) => x !== c) : [...state.capabilities, c]
                )
              }
            >
              {c}
            </Chip>
          ))}
        </div>
      </Field>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
        <Field label={`Temperature: ${state.temperature}`}>
          <input
            type="range"
            min="0"
            max="2"
            step="0.1"
            value={state.temperature}
            onChange={(e) => set("temperature", parseFloat(e.target.value))}
            style={{ width: "100%", accentColor: "#c8ff00" }}
          />
          <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: "#55556a" }}>
            <span>Precise</span><span>Creative</span>
          </div>
        </Field>
        <Field label="Max Tokens">
          <input style={monoInputStyle} type="number" value={state.maxTokens} onChange={(e) => set("maxTokens", parseInt(e.target.value) || 0)} />
        </Field>
      </div>
    </>
  );
}

function StepPrompt({ state, set }) {
  const lineCount = (state.promptContent || "").split("\n").length;
  return (
    <>
      <Field label="System Prompt (agent.md)" sub="The agent's brain — personality, instructions, guidelines">
        <div style={{ position: "relative" }}>
          <textarea
            style={{
              ...monoInputStyle,
              minHeight: 340,
              resize: "vertical",
              lineHeight: 1.7,
              fontSize: 12,
              padding: "16px 14px",
            }}
            value={state.promptContent}
            onChange={(e) => set("promptContent", e.target.value)}
            placeholder="You are a helpful AI assistant..."
          />
          <div style={{ position: "absolute", bottom: 8, right: 12, fontSize: 10, color: "#55556a" }}>
            {lineCount} lines · {(state.promptContent || "").length} chars
          </div>
        </div>
      </Field>
      <div style={{ fontSize: 11, color: "#55556a", padding: "8px 12px", background: "#111113", borderRadius: 8, border: "1px solid #222228" }}>
        💡 Tip: Use Markdown headers to organize sections. The prompt is saved as <code style={{ color: "#c8ff00" }}>agent.md</code> inside the .fylle package.
      </div>
    </>
  );
}

function StepInputs({ state, set }) {
  const addInput = () => set("inputs", [...state.inputs, { name: "", type: "text", required: false, description: "" }]);
  const removeInput = (i) => set("inputs", state.inputs.filter((_, idx) => idx !== i));
  const updateInput = (i, key, val) => {
    const next = [...state.inputs];
    next[i] = { ...next[i], [key]: val };
    set("inputs", next);
  };

  return (
    <>
      <Field label="Agent Inputs" sub="What the runtime must inject — makes the agent composable">
        {state.inputs.map((inp, i) => (
          <div key={i} style={{ display: "grid", gridTemplateColumns: "1fr 100px 80px 1fr 32px", gap: 8, alignItems: "center", marginBottom: 8 }}>
            <input style={monoInputStyle} placeholder="name" value={inp.name} onChange={(e) => updateInput(i, "name", e.target.value)} />
            <select style={{ ...inputStyle, padding: "10px 6px" }} value={inp.type} onChange={(e) => updateInput(i, "type", e.target.value)}>
              <option value="text">text</option>
              <option value="json">json</option>
              <option value="file">file</option>
              <option value="url">url</option>
            </select>
            <Chip active={inp.required} onClick={() => updateInput(i, "required", !inp.required)}>
              {inp.required ? "req" : "opt"}
            </Chip>
            <input style={inputStyle} placeholder="description" value={inp.description} onChange={(e) => updateInput(i, "description", e.target.value)} />
            {state.inputs.length > 1 && (
              <button onClick={() => removeInput(i)} style={{ background: "none", border: "none", color: "#ff6b8a", cursor: "pointer", fontSize: 16 }}>×</button>
            )}
          </div>
        ))}
        <SmallBtn onClick={addInput}>+ Add input</SmallBtn>
      </Field>
      <Field label="Output Format">
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
          {OUTPUT_FORMATS.map((f) => (
            <Chip key={f} active={state.outputFormat === f} onClick={() => set("outputFormat", f)}>{f}</Chip>
          ))}
        </div>
      </Field>
    </>
  );
}

function ToolList({ tools, setTools, label }) {
  const add = () => setTools([...tools, { name: "", protocol: "mcp", description: "", server: "" }]);
  const remove = (i) => setTools(tools.filter((_, idx) => idx !== i));
  const update = (i, key, val) => {
    const next = [...tools];
    next[i] = { ...next[i], [key]: val };
    setTools(next);
  };

  return (
    <Field label={label}>
      {tools.map((t, i) => (
        <div key={i} style={{ display: "grid", gridTemplateColumns: "1fr 90px 1fr 120px 32px", gap: 8, alignItems: "center", marginBottom: 8 }}>
          <input style={monoInputStyle} placeholder="tool name" value={t.name} onChange={(e) => update(i, "name", e.target.value)} />
          <select style={{ ...inputStyle, padding: "10px 6px" }} value={t.protocol} onChange={(e) => update(i, "protocol", e.target.value)}>
            {PROTOCOLS.map((p) => (
              <option key={p} value={p}>{p}</option>
            ))}
          </select>
          <input style={inputStyle} placeholder="description" value={t.description} onChange={(e) => update(i, "description", e.target.value)} />
          <input style={monoInputStyle} placeholder="server" value={t.server} onChange={(e) => update(i, "server", e.target.value)} />
          {tools.length > 0 && (
            <button onClick={() => remove(i)} style={{ background: "none", border: "none", color: "#ff6b8a", cursor: "pointer", fontSize: 16 }}>×</button>
          )}
        </div>
      ))}
      <SmallBtn onClick={add}>+ Add tool</SmallBtn>
    </Field>
  );
}

function StepTools({ state, set }) {
  return (
    <>
      <ToolList tools={state.toolsRequired} setTools={(v) => set("toolsRequired", v)} label="Required Tools" />
      <ToolList tools={state.toolsOptional} setTools={(v) => set("toolsOptional", v)} label="Optional Tools" />
      <div style={{ fontSize: 11, color: "#55556a", padding: "8px 12px", background: "#111113", borderRadius: 8, border: "1px solid #222228" }}>
        💡 Tools use <code style={{ color: "#a78bfa" }}>protocol: "mcp"</code> by default. The runtime maps tool names to available MCP servers. Optional tools degrade gracefully.
      </div>
    </>
  );
}

function StepGuardrails({ state, set }) {
  const addRule = () => set("guardrailsRules", [...state.guardrailsRules, ""]);
  const removeRule = (i) => set("guardrailsRules", state.guardrailsRules.filter((_, idx) => idx !== i));
  const updateRule = (i, val) => {
    const next = [...state.guardrailsRules];
    next[i] = val;
    set("guardrailsRules", next);
  };

  return (
    <>
      <Field label="Max Autonomy" sub="How much the agent can do without human approval">
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
          {AUTONOMY_LEVELS.map((l) => (
            <Chip key={l} active={state.maxAutonomy === l} onClick={() => set("maxAutonomy", l)}>{l}</Chip>
          ))}
        </div>
      </Field>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
        <Field label="Max Iterations">
          <input style={monoInputStyle} type="number" value={state.maxIterations} onChange={(e) => set("maxIterations", parseInt(e.target.value) || 0)} />
        </Field>
        <Field label="Max Tokens per Response">
          <input style={monoInputStyle} type="number" value={state.maxTokensPerResponse} onChange={(e) => set("maxTokensPerResponse", parseInt(e.target.value) || 0)} />
        </Field>
      </div>
      <Field label="Rules" sub="Behavioral constraints for the agent">
        {state.guardrailsRules.map((r, i) => (
          <div key={i} style={{ display: "flex", gap: 8, marginBottom: 8 }}>
            <input style={inputStyle} placeholder="e.g. Never make claims without a source" value={r} onChange={(e) => updateRule(i, e.target.value)} />
            {state.guardrailsRules.length > 1 && (
              <button onClick={() => removeRule(i)} style={{ background: "none", border: "none", color: "#ff6b8a", cursor: "pointer", fontSize: 16 }}>×</button>
            )}
          </div>
        ))}
        <SmallBtn onClick={addRule}>+ Add rule</SmallBtn>
      </Field>
    </>
  );
}

function StepMemory({ state, set }) {
  const addField = () => set("memoryFields", [...state.memoryFields, { name: "", type: "text", description: "" }]);
  const removeField = (i) => set("memoryFields", state.memoryFields.filter((_, idx) => idx !== i));
  const updateField = (i, key, val) => {
    const next = [...state.memoryFields];
    next[i] = { ...next[i], [key]: val };
    set("memoryFields", next);
  };

  return (
    <>
      <Field label="Enable Memory">
        <Chip active={state.memoryEnabled} onClick={() => set("memoryEnabled", !state.memoryEnabled)}>
          {state.memoryEnabled ? "Enabled" : "Disabled"}
        </Chip>
      </Field>
      {state.memoryEnabled && (
        <>
          <Field label="Persistence" sub="How the runtime manages memory storage">
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
              {PERSISTENCE_OPTS.map((p) => (
                <Chip key={p} active={state.memoryPersistence === p} onClick={() => set("memoryPersistence", p)}>{p}</Chip>
              ))}
            </div>
          </Field>
          <Field label="Memory Schema" sub="What the agent remembers — the runtime decides how">
            {state.memoryFields.map((f, i) => (
              <div key={i} style={{ display: "grid", gridTemplateColumns: "1fr 100px 1fr 32px", gap: 8, alignItems: "center", marginBottom: 8 }}>
                <input style={monoInputStyle} placeholder="field name" value={f.name} onChange={(e) => updateField(i, "name", e.target.value)} />
                <select style={{ ...inputStyle, padding: "10px 6px" }} value={f.type} onChange={(e) => updateField(i, "type", e.target.value)}>
                  <option value="text">text</option>
                  <option value="list">list</option>
                  <option value="json">json</option>
                  <option value="number">number</option>
                </select>
                <input style={inputStyle} placeholder="description" value={f.description} onChange={(e) => updateField(i, "description", e.target.value)} />
                {state.memoryFields.length > 1 && (
                  <button onClick={() => removeField(i)} style={{ background: "none", border: "none", color: "#ff6b8a", cursor: "pointer", fontSize: 16 }}>×</button>
                )}
              </div>
            ))}
            <SmallBtn onClick={addField}>+ Add field</SmallBtn>
          </Field>
        </>
      )}
    </>
  );
}

function StepPreview({ state }) {
  const yaml = generateYAML(state);
  const agentMd = generateAgentMd(state);
  const [copied, setCopied] = useState(false);
  const [tab, setTab] = useState("manifest");

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const currentContent = tab === "manifest" ? yaml : agentMd;

  return (
    <>
      <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
        <Chip active={tab === "manifest"} onClick={() => setTab("manifest")}>manifest.yaml</Chip>
        <Chip active={tab === "agent"} onClick={() => setTab("agent")}>agent.md</Chip>
      </div>
      <div style={{ position: "relative" }}>
        <pre
          style={{
            background: "#0a0a0b",
            border: "1px solid #222228",
            borderRadius: 10,
            padding: 20,
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: 11.5,
            lineHeight: 1.7,
            color: "#c8ff00",
            overflowX: "auto",
            maxHeight: 440,
            whiteSpace: "pre-wrap",
            wordBreak: "break-word",
          }}
        >
          {currentContent}
        </pre>
        <button
          onClick={() => copyToClipboard(currentContent)}
          style={{
            position: "absolute",
            top: 10,
            right: 10,
            padding: "6px 14px",
            fontSize: 11,
            fontWeight: 600,
            background: copied ? "#c8ff0020" : "#16161a",
            border: "1px solid #333340",
            borderRadius: 6,
            color: copied ? "#c8ff00" : "#8888a0",
            cursor: "pointer",
          }}
        >
          {copied ? "Copied ✓" : "Copy"}
        </button>
      </div>
      <div style={{ marginTop: 16, display: "flex", gap: 12 }}>
        <button
          onClick={() => {
            const blob = new Blob([yaml], { type: "text/yaml" });
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `${state.name || "agent"}-manifest.yaml`;
            a.click();
            URL.revokeObjectURL(url);
          }}
          style={{
            padding: "12px 24px",
            background: "#c8ff00",
            color: "#0a0a0b",
            border: "none",
            borderRadius: 8,
            fontSize: 14,
            fontWeight: 700,
            cursor: "pointer",
          }}
        >
          ↓ Download manifest.yaml
        </button>
        <button
          onClick={() => {
            const blob = new Blob([agentMd], { type: "text/markdown" });
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = "agent.md";
            a.click();
            URL.revokeObjectURL(url);
          }}
          style={{
            padding: "12px 24px",
            background: "transparent",
            color: "#e8e8ed",
            border: "1px solid #333340",
            borderRadius: 8,
            fontSize: 14,
            fontWeight: 600,
            cursor: "pointer",
          }}
        >
          ↓ Download agent.md
        </button>
      </div>
    </>
  );
}

export default function FylleBuilder() {
  const [step, setStep] = useState(0);
  const [state, setState] = useState(defaultState);

  const set = useCallback((key, val) => setState((prev) => ({ ...prev, [key]: val })), []);

  const currentStep = STEPS[step];
  const canNext = step < STEPS.length - 1;
  const canPrev = step > 0;

  const completionPct = useMemo(() => {
    let filled = 0;
    let total = 5;
    if (state.name) filled++;
    if (state.description) filled++;
    if (state.promptContent && state.promptContent.length > 30) filled++;
    if (state.inputs.some((i) => i.name)) filled++;
    if (state.toolsRequired.some((t) => t.name)) filled++;
    return Math.round((filled / total) * 100);
  }, [state]);

  const renderStep = () => {
    switch (currentStep.id) {
      case "identity": return <StepIdentity state={state} set={set} />;
      case "model": return <StepModel state={state} set={set} />;
      case "prompt": return <StepPrompt state={state} set={set} />;
      case "inputs": return <StepInputs state={state} set={set} />;
      case "tools": return <StepTools state={state} set={set} />;
      case "guardrails": return <StepGuardrails state={state} set={set} />;
      case "memory": return <StepMemory state={state} set={set} />;
      case "preview": return <StepPreview state={state} />;
      default: return null;
    }
  };

  return (
    <div style={{ minHeight: "100vh", background: "#0a0a0b", color: "#e8e8ed", fontFamily: "'Instrument Sans', system-ui, sans-serif" }}>
      {/* Header */}
      <div style={{ borderBottom: "1px solid #222228", padding: "16px 24px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <Link to="/" style={{ fontFamily: "'JetBrains Mono', monospace", fontWeight: 700, color: "#c8ff00", fontSize: 16, textDecoration: "none" }}>Fylle</Link>
          <span style={{ color: "#333340" }}>|</span>
          <span style={{ color: "#55556a", fontSize: 13 }}>Builder</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <div style={{ width: 120, height: 4, background: "#222228", borderRadius: 2, overflow: "hidden" }}>
              <div style={{ width: `${completionPct}%`, height: "100%", background: "#c8ff00", borderRadius: 2, transition: "width 0.3s" }} />
            </div>
            <span style={{ fontSize: 11, color: "#55556a", fontFamily: "'JetBrains Mono', monospace" }}>{completionPct}%</span>
          </div>
          <a href="https://github.com/DavideScanta/fylle-format" target="_blank" rel="noopener noreferrer" style={{ color: "#8888a0", fontSize: 12, textDecoration: "none", fontWeight: 500, padding: "6px 12px", border: "1px solid #222228", borderRadius: 6, transition: "all 0.15s" }}>
            Spec ↗
          </a>
        </div>
      </div>

      <div style={{ display: "flex", minHeight: "calc(100vh - 57px)" }}>
        {/* Sidebar */}
        <div style={{ width: 200, borderRight: "1px solid #222228", padding: "16px 0", flexShrink: 0 }}>
          {STEPS.map((s, i) => (
            <button
              key={s.id}
              onClick={() => setStep(i)}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                width: "100%",
                padding: "10px 20px",
                background: i === step ? "#c8ff0010" : "transparent",
                border: "none",
                borderRight: i === step ? "2px solid #c8ff00" : "2px solid transparent",
                color: i === step ? "#c8ff00" : i < step ? "#8888a0" : "#55556a",
                fontSize: 13,
                fontWeight: i === step ? 600 : 400,
                cursor: "pointer",
                textAlign: "left",
                fontFamily: "inherit",
                transition: "all 0.15s",
              }}
            >
              <span style={{ fontSize: 14, width: 20, textAlign: "center" }}>{s.icon}</span>
              {s.label}
            </button>
          ))}
        </div>

        {/* Main */}
        <div style={{ flex: 1, padding: "32px 40px", maxWidth: 800, overflowY: "auto" }}>
          <div style={{ marginBottom: 28 }}>
            <div style={{ fontSize: 11, fontFamily: "'JetBrains Mono', monospace", color: "#c8ff00", textTransform: "uppercase", letterSpacing: 2, marginBottom: 6 }}>
              Step {step + 1} of {STEPS.length}
            </div>
            <h2 style={{ fontSize: 24, fontWeight: 700, letterSpacing: -0.5 }}>{currentStep.label}</h2>
          </div>

          {renderStep()}

          {/* Nav buttons */}
          <div style={{ display: "flex", justifyContent: "space-between", marginTop: 32, paddingTop: 20, borderTop: "1px solid #222228" }}>
            <button
              onClick={() => canPrev && setStep(step - 1)}
              disabled={!canPrev}
              style={{
                padding: "10px 24px",
                background: "transparent",
                border: "1px solid #222228",
                borderRadius: 8,
                color: canPrev ? "#e8e8ed" : "#333340",
                fontSize: 13,
                fontWeight: 600,
                cursor: canPrev ? "pointer" : "default",
                fontFamily: "inherit",
              }}
            >
              ← Back
            </button>
            {canNext && (
              <button
                onClick={() => setStep(step + 1)}
                style={{
                  padding: "10px 24px",
                  background: "#c8ff00",
                  border: "none",
                  borderRadius: 8,
                  color: "#0a0a0b",
                  fontSize: 13,
                  fontWeight: 700,
                  cursor: "pointer",
                  fontFamily: "inherit",
                }}
              >
                Next →
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
